CREATE TABLE EMPLOYEES  ( 
	EMPLOYEE_ID     	int(11) NOT NULL,
	EMPLOYEE_NAME   	varchar(25) NOT NULL,
	EMPLOYEE_SURNAME	varchar(25) NOT NULL,
	PRIMARY KEY(EMPLOYEE_ID)
)
GO

CREATE TABLE EMPLOYEES_SALARY  ( 
	EMPLOYEE_ID	decimal(10,0) NOT NULL,
	SALARY     	float NULL 
	)
GO